Add the functionality of django invitation
brylie/wagtail-social-network pull request #29
Opened 2021-08-17 12:01 UTC by Upasanadhameliya

Closes #21 

- Added the initial project structure for enabling the users to send invitations to their friends.
- Included `django-invitations` in the settings of the project for its usage.
- Currently included the models in the `home` app but might want to change it.

2021-08-17 12:36 UTC, brylie commented on project/core/settings/base.py
> +EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
Let's use the [django.core.mail.backends.filebased.EmailBackend](https://docs.djangoproject.com/en/3.2/topics/email/#console-backend) for development. The console backend seems to already be defined in our development settings:

https://github.com/brylie/wagtail-social-network/blob/af655ccd52a0686c069dbe45551d504ee3d93c5c/project/core/settings/dev.py#L12

Is the email console backend not working in the development environment?

2021-08-17 12:38 UTC, Upasanadhameliya commented on project/core/settings/base.py
> +EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
Yes the mails are not getting sent for some reason, you might want to try and debug it..

2021-08-17 12:49 UTC, brylie requested changes

2021-08-17 12:49 UTC, brylie commented on project/home/templates/home/invite_friends.html
> +        <p><input type="submit" value="Send Invitation Now!"></p>
Let's use [Bootstrap button classes](https://getbootstrap.com/docs/4.0/components/buttons/) so this renders as a button.

```suggestion
        <p><input type="submit" class="btn btn-primary" value="Send Invitation Now!"></p>
```

2021-08-17 12:49 UTC, brylie commented on project/home/templates/home/home_page.html
> +            <h4><a href="{% pageurl invite_friend %}">{{ invite_friend.title }}</a></h4>
Use semantic markup for headers. I.e. use the correct header hierarchy for the document rather than using lower-level headers to change font size.

- `h1` - there should be only one `h1` per page
  - `h2` - there should be `h1` above `h2`
    - `h3` - there should be `h2` through `h1` above `h3`
      - `h4` - there should be `h1` through `h3` above `h4`

```suggestion
            <h2><a href="{% pageurl invite_friend %}">{{ invite_friend.title }}</a></h2>
```

2021-08-17 12:49 UTC, brylie commented on project/home/models.py
> +                    # 'flavour': friend_invite,
Remove unused code:

```suggestion
```

2021-08-17 12:49 UTC, brylie commented on project/core/settings/base.py
> +EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
OK, I'll check it out to see why the dev settings don't seem to apply in our local environment

2021-08-17 12:52 UTC, brylie requested changes
Remember to `pip freeze > requirements.txt`

Perhaps we might consider switching to Poetry at some point

2021-08-17 13:13 UTC, brylie commented on project/core/settings/base.py
> +EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
It looks like we need to set a local environment variable called `DJANGO_SETTINGS_MODULE` with the value of `core.settings.dev` when running the project locally.

I'll open a follow-up task to create documentation for using the development settings, with the option of using a `.env` file to make it slightly easier.

2021-08-18 09:01 UTC, Upasanadhameliya commented on project/core/settings/base.py
> +EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
I changed the `EMAIL_BACKEND` variable. However the actual mail from any server are not getting sent currently to any email id.

2021-08-18 09:34 UTC, brylie commented on project/home/templates/home/home_page.html
> +        <div style="text-align: right;">
Bootstrap has [utility classes to float elements](https://getbootstrap.com/docs/4.0/utilities/float/#classes).

```suggestion
        <div class="float-right">
```

2021-09-22 10:20 UTC, Upasanadhameliya commented on project/core/settings/base.py
> +EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
@brylie Currently in the terminal/console the following message gets displayed upon clicking `send invitations` button

```
example.email@gmail.com
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: [example.com] Invitation to join example.com
From: webmaster@localhost
To: example.email@gmail.com
Date: Wed, 22 Sep 2021 10:15:41 -0000
Message-ID: <163230574123.6284.496223274602170681@TRD1069>

Hello,

You (example.email@gmail.com) have been invited to join example.com

If you'd like to join, please go to http://localhost:8000/invitations/accept-invite/jvfl44k3lmcwbcqqv5bp1zn5qhrxpktya1rdbs0q3vq4p7nzh1m2ytkrheichit4
```

2021-09-22 10:29 UTC, brylie commented
@Upasanadhameliya this is looking great! Is the pull request ready for review or should it still be in the draft state?

2021-09-22 10:31 UTC, Upasanadhameliya commented
@brylie It's ready for review!

2021-09-22 11:14 UTC, brylie requested changes

2021-09-22 11:14 UTC, brylie commented on project/home/models.py
> +
Adding `max_count = 1` will make it so only once instance of this page can be added, which makes sense since there is only one "Invite Friends" page.

```suggestion
max_count = 1
```

2021-09-22 11:14 UTC, brylie commented on project/home/models.py
> +class InviteFriendsPage(Page):
Let's move this class to the `invitations` app `models.py`

2021-09-22 11:14 UTC, brylie commented on project/home/forms.py
> +class FriendInvitationForm(forms.ModelForm):
Move this form to `invitations` app `forms.py`

2021-09-22 11:14 UTC, brylie commented on project/home/models.py
> +        context['invite_friends'] = self.get_children().type(InviteFriendsPage)
If we set `max_count = 1` on the `InviteFriendsPage` model, we can get the _only_ instance using `InviteFriendsPage.objects.get()`
```suggestion
        context['invite_friends_page'] = InviteFriendsPage.objects.get()
```

2021-09-22 11:14 UTC, brylie commented on project/home/templates/home/home_page.html
> +            <h2><a href="{% pageurl invite_friend %}">{{ invite_friend.title }}</a></h2>
Slightly more explicit:

```suggestion
            <h2><a href="{% pageurl invite_friend %}">{{ invite_friends_page.title }}</a></h2>
```

2021-09-22 11:14 UTC, brylie commented on project/home/templates/home/thankyou.html
> +    <h1> Thanks for inviting!</h1>
```suggestion
    <h1>Thanks for inviting your friend!</h1>
```

2021-09-22 11:14 UTC, brylie commented on project/home/templates/home/thankyou.html
> +    <p><a href="{{ page.get_parent.url }}">Return to home</a></p>
```suggestion
    <p><a href="{{ page.get_parent.url }}">Return to home page</a></p>
```

2021-09-22 11:14 UTC, brylie commented on project/home/models.py
> +    email = models.EmailField(max_length=254,blank=True,default=None)
Move to `invitations` app `models.py`

2021-09-23 04:07 UTC, Upasanadhameliya commented on project/home/models.py
> +class InviteFriendsPage(Page):
@brylie we already have an app named `invitations` as we are using the functionality of `django-invitations`. Hence, I can't create a new app with the same name due to name conflicts. So I am thinking of creating an app named `invite` to our project. Hope this is okay, feel free to give suggestions 😄

2021-09-23 08:44 UTC, brylie commented on project/core/settings/base.py
> +EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
That looks good. It will only output to the terminal during development, which is desirable.

2021-09-23 08:46 UTC, brylie commented on project/home/models.py
> +class InviteFriendsPage(Page):
Yep, `invite` is fine. 

As a general rule, which we can break here, Django app names are plural. So, `invitations` would be more desirable, but is already taken as you note.

2021-09-23 11:58 UTC, Upasanadhameliya commented on project/home/models.py
> +class InviteFriendsPage(Page):
Okay I will try to make it as `invites`

2021-09-24 04:27 UTC, Upasanadhameliya commented
@brylie I have pushed new changes and made the requested changes. You can review and, if no other changes are required, merge the pr.

2021-09-24 10:12 UTC, brylie commented on project/core/settings/base.py
> +    'invites',
Let's keep the custom apps in `INSTALLED_APPS` in alphabetical order.

```suggestion
    'home',
    'invites',
    'search',
```

2021-09-24 10:22 UTC, brylie requested changes
Just a few minor changes. Otherwise, looking great.

By the way, we should consider how to internationalize page texts, so this project works in other languages than English :-)

2021-09-24 10:22 UTC, brylie commented on project/invites/models.py
> +                print(invite_obj.email)
Remove `print` statement(s) when no longer needed.
```suggestion
```

2021-09-24 10:22 UTC, brylie commented on project/invites/models.py
> +                form = invitations.utils.get_invite_form()()
The double parenthesis is subtle and may lead to unexpected behavior. Let's add a comment to emphasize we are doing two actions with one line here.

```suggestion
                # Get invitation form class and create instance
                form = invitations.utils.get_invite_form()()
```

2021-09-24 10:22 UTC, brylie commented on project/invites/models.py
> +                print(invite_obj.email)
Clean up print statement(s).
```suggestion
```

2021-09-24 10:22 UTC, brylie commented on project/invites/models.py
> +                })
Use `black` to format code.
```suggestion
            return render(request, 'invites/thankyou.html', {
                'page': self,
            })
```

2021-09-29 06:08 UTC, Upasanadhameliya commented
@brylie I have made the requested changes. Do you want me to work on internationalizing page texts in this pull request or do it in other pr?

2021-09-29 17:30 UTC, brylie commented
Let's create a new issue for internationalizing page texts across the project. There may be other places we discover that are missing i18n tags.

Great work! :smiley:

2021-09-29 17:31 UTC, merged