Improved the `CONTRIBUTING.md` a little bit.
brylie/wagtail-social-network pull request #32
Opened 2021-08-17 17:10 UTC by CodeBunny09

Hey, I added the DJANGO_SETTINGS_MODULE thingy in the CONTRIBUTING.md and changed it a lil bit.....

2021-08-18 09:01 UTC, brylie requested changes

2021-08-18 09:01 UTC, brylie commented on CONTRIBUTING.md
> +You can use it by changing the `manage.py` file in `project` directory and `wsgi.py` in `project/core` directory.
It would be better to tell people how to set the environment variables in their shell to avoid these changes being committed to the codebase. In effect, these development settings should not be part of the project code since we want to deploy the code to a production server eventually. Would you mind changing the documentation to describe how to set the local environment variable?

2021-08-18 14:51 UTC, CodeBunny09 commented on CONTRIBUTING.md
> +You can use it by changing the `manage.py` file in `project` directory and `wsgi.py` in `project/core` directory.
sure

2021-08-18 15:37 UTC, CodeBunny09 commented
I did explain how to change the settings using environment variables in my new commit, ty for the feedback... 😄😄

2021-08-20 12:22 UTC, brylie approved these changes
Great work! Thanks :-)

2021-08-20 12:22 UTC, merged

2021-08-20 12:22 UTC, brylie commented
@all-contributors please add @CodeBunny09 for docs