Add external links to Chapter Profile
brylie/wagtail-social-network pull request #37
Opened 2021-10-26 06:26 UTC by Upasanadhameliya

## What?
#### Backend
- Created a base model called `Groups`. 
- Made `Chapters` a child model class of `Groups`
- Added Many-To-Many relationship in Groups with `members` and `users`. Many `users` can be a part of a `group` and a `user` can be involved in multiple `groups`.
- Chapters objects were added to `context` after ordering by `region` and `name`. This was essential for the correct display through [regroup template tag.](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#:~:text=Note%20that%20%7B%25%20regroup%20%25%7D%20does%20not%20order%20its%20input!)
- Added functionality for users to join and leave a `Group`.
- Added `GroupsIndexPage` from which `ChaptersIndexPage` inherits.
#### Frontend
- Added **Chapters Index Page** link to the **Home Page**
- Added **Chapters Page** containing chapter **title**, Join/leave **button** and **link** to previous page.
#### Chapters Display on Chapters Index Page
![ques71](https://user-images.githubusercontent.com/28010398/141052212-09f9dae0-b225-480d-8b69-b940373c45bf.png)

2021-11-01 04:16 UTC, Upasanadhameliya commented
@brylie so should I make this pull request ready for review? Is there any additional change you would like me to implement before I do so?

2021-11-01 07:43 UTC, brylie commented
Yeah, let's mark this as ready for review. If you agree that the AJAX would be a good enhancement for the group membership button, please open a feature request, so we remember to come back around to that enhancement.

2021-11-02 08:04 UTC, brylie requested changes

2021-11-02 08:04 UTC, brylie commented on project/chapters/models.py
> +        if request.GET.get("join", "False").lower() == "true":
I believe we should use POST here with a CSRF token to discourage abuse of this feature. E.g. someone might send out links to "view our group" with the "join=true" in the URL so that people automatically join when clicking the link. Also, GET is intended for 

The Django forms framework offers good protection and will deserialize data into Python data types (such as boolean) for us as well.

I think we should switch this implementation to use Django forms, using a similar conditional to what you have already written:


```py
// in chapters/forms.py
from django import forms

class GroupMembershipForm(forms.Form):
    MEMBERSHIP_ACTION_CHOICES = [("join", "Join"), ("leave", "Leave")]

    membership_action = forms.ChoiceField(label='Membership action', choices=MEMBERSHIP_ACTION_CHOICES)
```

```py
// in chapters/models.py Groups.serve()
from .forms import GroupMembershipForm

...
serve(self, request, *args, **kwargs):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = GroupMembershipForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            // handle membership action
            if form.membership_action == "join":
                self.members.add(request.user)
            else:
                self.members.remove(request.user)
...
```

We can render only a submit button with the appropriate label as well as a hidden `membership_action` field somewhat like below:

```html
<!-- in chapters/templates/chapters/chapters.html -->

<form action="." method="post">
    {% csrf_token %}
    
    {% if user in page.members.all() %}
        <input id="membership_action" type="hidden" name="membership_action" value="join">
        <input type="submit" value="Join group">
    {% else %}
        <input id="membership_action" type="hidden" name="membership_action" value="leave">
        <input type="submit" value="Leave group">
    {% endif %}
</form>
```

The above example is basically pseudo-code, but may serve to illustrate the idea.

Related reading: [Why shouldn't a GET request change data on the server?](https://softwareengineering.stackexchange.com/questions/188860/why-shouldnt-a-get-request-change-data-on-the-server)

2021-11-02 08:13 UTC, brylie requested changes

2021-11-02 08:13 UTC, brylie commented on project/chapters/models.py
> +    subpage_types = []
We should consider the URL design here. Since we are using the Wagtail `Page` model there are a couple of things to consider:

- the `Page`-based content model is hierarchical, creating a tree of `Page`s
- the content hierarchy translates directly to the URL structure:
  - e.g. `root-page/child-page/child-of-child-page/

So, setting the `subpage_types` and `parent_page_types` values allows us to have a clean URL/`Page` hierarchy, rather than having all content in the root namespace or organized in an ad-hoc manner.

One hypothetical URL structure might be:

- `/chapters/<chapter-name-slug>`
- `/groups/<group-name-slug>`

The above structure, including the page slugs, would be handled by Wagtail without any URL configuration.

Further reading:

- Wagtail: Page models - [Parent page / subpage type rules](https://docs.wagtail.io/en/stable/topics/pages.html#parent-page-subpage-type-rules)

2021-11-03 09:40 UTC, brylie requested changes

2021-11-03 09:40 UTC, brylie commented on project/chapters/templates/chapters/chapter.html
> +        <input type="submit" class="btn btn-primary"value="Join group">
Let's add i18n support here
```suggestion
        <input type="submit" class="btn btn-primary"value="{% translate 'Join group' %}">
```

2021-11-03 09:40 UTC, brylie commented on project/chapters/templates/chapters/chapter.html
> +        <input type="submit" class="btn btn-secondary" value="Leave group">
Remember i18n
```suggestion
        <input type="submit" class="btn btn-secondary" value="{% translate 'Leave group' %}">
```

2021-11-03 09:40 UTC, brylie commented on project/chapters/templates/chapters/chapter.html
>  <p><a href="{{ page.get_parent.url }}">Return to {{ page.get_parent.title }} Page </a></p>
While we didn't create this line as part of this pull request, I'd like to consider a few of nuances here:

-  a link to the parent page wouldn't necessarily "return" the user to where they have already been
- we need to consider our URL hierarchy, since the parent page for all groups may be the Group Index page or we may allow hierarchical groups
- in any case, we need to support internationalization for all UI texts in as simple of a way as possible, so we may want to avoid having a variable in the link text

Let's clean up this line while we are working in this file. The simplest way may be to just delete the line.

```suggestion
```

2021-11-03 09:41 UTC, brylie commented on project/chapters/models.py
> +    subpage_types = []
One key decision is whether to support hierarchical groups, or to have all groups registered in the same "branch" of the Wagtail Page tree. I.e. 

- `groups/<group-slug/`, or
- `groups/<parent-group-slug>/<child-group-slug>/.../...`

2021-11-03 09:42 UTC, brylie commented on project/chapters/models.py
> +    subpage_types = []
A flat content model may be simpler to deal with and would avoid deeply nested URLs. What are your thoughts?

2021-11-08 04:10 UTC, Upasanadhameliya commented on project/chapters/models.py
> +    subpage_types = []
I am in favour with the latter type of a `flat` structure as you suggested. However, I haven't really thought on how I can implement such a structure. 

Also, I think the documentation is lacking on this topic, so if you would like to change the structure of the pages as  `groups/<parent-group-slug>/<child-group-slug>/.../...` can you provide any useful links that might help me get an idea on how to do so?

As per my understanding, some examples of the flat structure that you are suggesting would be: 
- `groups/chapters/india`
- `groups/chapters/sweden`
- `groups/ice-creams/vanilla`
- `groups/ice-creams/chocolate`

Are my examples correctly representing the idea that you are suggesting?

2021-11-08 12:14 UTC, brylie commented on project/chapters/models.py
> +    subpage_types = []
For the flat structure, we just need to define [Wagrail parent page and subpage type rules](https://docs.wagtail.io/en/stable/topics/pages.html#parent-page-subpage-type-rules).

Specifically, the GroupIndexPage would only allow Groups as sub page types while the Group model would only allow the GroupIndexPage as a parent page type. The Group model wouldn't allow any subpage types, an empty list, so groups would be flat.

2021-11-08 12:15 UTC, brylie commented on project/chapters/models.py
> +    subpage_types = []
In general, we are writing idiomatic Django and Wagtail code so their respective documentation should be our primary reference.

2021-11-09 04:59 UTC, Upasanadhameliya commented on project/chapters/models.py
> +    subpage_types = []
> Specifically, the GroupIndexPage would only allow Groups as sub page types while the Group model would only allow the GroupIndexPage as a parent page type. The Group model wouldn't allow any subpage types, an empty list, so groups would be flat.

@brylie so do you the `ChaptersIndexPage` to inherit from `GroupIndexPage` just like `Chapters` are being inherited from `Groups` ?

2021-11-09 07:21 UTC, brylie commented on project/chapters/models.py
> +    subpage_types = []
That might be a good architecture if the `GroupIndexPage` code, such as `get_context` is useful on the `ChaptersIndexPage` and template. It seems like the two index pages are 99% similar in functionality so inheritance might make the code a bit easier to maintain.

2021-11-10 09:50 UTC, brylie requested changes

2021-11-10 09:50 UTC, brylie commented on project/chapters/models.py
> +            Chapter.objects.child_of(self).live().order_by(*self.context_order)
This may be a typo since we are in the `GroupsIndexPage` class. It might be possible to make it a bit more generic since we have restricted the `<Group|Chapter>IndexPage` model `subpage_types` to allow only `Group` or `Chapter` both of which inherit from `Page`:

```suggestion
            Page.objects.child_of(self).live().order_by(*self.context_order)
```

2021-11-10 09:53 UTC, brylie requested changes

2021-11-10 09:53 UTC, brylie commented on project/chapters/models.py
> +        """
Docstring should be the first line within the function
```suggestion
        """
        If user is a member display the greyed out button using
        the "context.member" variable, else display blue button
        for joining group
        """
        
        context = super().get_context(request, *args, **kwargs)
```

2021-11-10 09:59 UTC, brylie requested changes

2021-11-10 09:59 UTC, brylie commented on project/chapters/models.py
> +        return context
Let's shorten this code and comment a bit for clarity:

```suggestion
        context = super().get_context(request, *args, **kwargs)
       
        # Check whether request user is a member of current group
        context["member"] = request.user in self.members.all()

        return context
```

2021-11-10 10:01 UTC, brylie requested changes

2021-11-10 10:01 UTC, brylie commented on project/chapters/models.py
> +        # If query argument "join" is passed as true then add member
The comment is no longer relevant here.

```suggestion
```

2021-11-10 10:02 UTC, brylie requested changes

2021-11-10 10:02 UTC, brylie commented on project/chapters/models.py
> +            if form.is_valid():
A comment is unnecessary since this code is self-documenting.
```suggestion

            if form.is_valid():
```

2021-11-10 10:04 UTC, brylie commented on project/chapters/models.py
> +                    return redirect("login")
I'm just thinking here that an anonymous user might click "join" and then be redirected to login. What happens after they log in?

To avoid the above situation, perhaps we shouldn't show the join button to users who aren't authenticated.

2021-11-10 10:12 UTC, brylie requested changes

2021-11-10 10:12 UTC, brylie commented on project/chapters/templates/chapters/chapter.html
> +</form>
To avoid confusion, anonymous users shouldn't see this form
```suggestion
{% if user.is_authenticated %}
<form action="." method="post">
    {% csrf_token %}
    {% if member == False %}
        <input id="membership_action" type="hidden" name="membership_action" value="join">
        <input type="submit" class="btn btn-primary"value="{% translate 'Join group' %}">
    {% else %}
        <input id="membership_action" type="hidden" name="membership_action" value="leave">
        <input type="submit" class="btn btn-secondary" value="{% translate 'Leave group' %}">
    {% endif %}
</form>
{% endif %}
```

2021-11-10 10:13 UTC, brylie commented on project/chapters/models.py
> +                    return redirect("login")
I've added a code suggestion to the template to hide the "join group" form from anonymous users.

2021-11-10 10:16 UTC, brylie requested changes

2021-11-10 10:16 UTC, brylie commented on project/home/templates/home/home_page.html
> +    {% with chapters_index_page=chapters_index_page.specific %}
From what I understand, it shouldn't be necessary to use the `.specific` attribute, but I may be mistaken. Let's try without `.specific` and see if this still works.
```suggestion
    {% with chapters_index_page=chapters_index_page %}
```

2021-11-10 10:16 UTC, brylie commented
The overall direction and code architecture here look great! There are just a few minor considerations that I've mentioned in the review comments.

2021-11-11 05:39 UTC, Upasanadhameliya commented on project/home/templates/home/home_page.html
> +    {% with chapters_index_page=chapters_index_page.specific %}
It still works! 😸

2021-11-11 08:19 UTC, brylie approved these changes

2021-11-11 08:20 UTC, merged

2021-11-11 08:21 UTC, brylie commented
Great work! This is a significant PR :-)

2021-11-11 09:48 UTC, Upasanadhameliya commented
Yeah thank you! 😄