Add language chooser menu
brylie/wagtail-social-network pull request #44
Opened 2021-11-29 04:24 UTC by Upasanadhameliya

Closes #39

2021-11-30 09:45 UTC, brylie requested changes
This is quite a lot of languages to support from the start. Let's pick a couple of initial languages and add more incrementally. Do you speak any languages other than English? If so, would you like to provide the first localization for our project? We can enable the languages you speak and create a separate task to localize the text. Then, we can add languages based on widespread usage as well as the availability of localization help.

2021-12-01 04:21 UTC, Upasanadhameliya commented
@brylie I am able to speak and read `Hindi (hi)` besides English. Any other language you want to keep besides this?

2021-12-01 08:44 UTC, brylie commented
OK, cool! Let's create a follow-up task for Hindi localization :-)

2021-12-02 09:40 UTC, brylie requested changes

2021-12-02 09:40 UTC, brylie commented on project/core/templates/navbar.html
> +            </li>
Let's use the example from the Django [set language set_language redirect view](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#the-set-language-redirect-view) docs

```html
{% load i18n %}

<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go">
</form>
```

Make sure to read the docs carefully and remember to 
- set the `i18n` URLs
- define the list of supported languages, if needed

2021-12-03 07:14 UTC, brylie approved these changes

2021-12-03 07:15 UTC, merged